name: Build, Test, and Push Docker Image

on:
  push:
    branches:
    - main # Change this to your main branch name

jobs:
  build-test-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
  
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME_MIDLABADP }}
        password: ${{ secrets.DOCKERHUB_TOKEN_MIDLABADP }}

    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: MidLabADP
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME_MIDLABADP }}/my_app:latest